### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by p0nce** [ZILtoid1991/pixelperfectengine#22]
In a clean checkout on Windows, LDC 1.33, DMD 2.104

- recommended example doesn't build
![image](https://github.com/ZILtoid1991/pixelperfectengine/assets/1067485/6c2ca8fe-81d3-458a-b00c-58cb50f773de)

- not clear how to run the tests, didn't find the DUB command to do so
- test do not link with LDC 1.33 
![image](https://github.com/ZILtoid1991/pixelperfectengine/assets/1067485/6f2e8c2f-071d-4506-8136-469e19e368a0)

  I can make most things build instead by removing lines like that from dub.sdl:
  `lflags "/PDB:.\\bin-$ARCH-$PLATFORM\\pixelperfectengine_xxxx.pdb" platform="windows"`
  necessary for all tests and the editor.

- using DMD instead, we can see the use of `intel-intrinsics-1.3.5` doesn't build with it. But latest intel-intrinsics ~>1.0 most likely would
![image](https://github.com/ZILtoid1991/pixelperfectengine/assets/1067485/ae86d39c-59b6-45b9-849c-5f7263bf69a0)

- not clear that pixelperfecteditor must be checkouted inside pixelperfectengine/ checkout.
- when running pixelperfecteditor: `std.exception.ErrnoException@std\stdio.d(639): Cannot open file `../system/concreteGUIE6.tga' in mode `rb' (No such file or directory)` this wasn't added probably
- after `std.exception.ErrnoException@std\stdio.d(639): Cannot open file `../system/dylex-6x10.fnt' in mode `rb' (No such file or directory)`

**Comment by emil-perhinschi** [comment]
had some of these problems on Linux too, for example a few "Cannot open file ../system" errors, which I solved by removing the "../" part in the code then the test I built ("test0") did not run because it could not find assets and .sdl files so I had to copy the proper folders in the build folder, then the executable worked fine 

I assumed I'm doing something wrong :-)

**Comment by ZILtoid1991** [comment]
I did some update to the README.md file to reflect these things.

Your binaries should normally go to the `./bin-[CPUarch]-[OS]/` folder, but I'll make some functions to generate paths to certain assets, which will be especially important for closed platforms, like consoles and smartphones.
