### ISSUE TITLE
Unable to compile on Linux

### ISSUE THREAD

**Issue by Raccoon-JS** [ZILtoid1991/pixelperfectengine#9]
I used 'dub' to compile this but received this message.

`Performing "debug" build using /usr/bin/dmd for x86_64.
pixelperfectengine 0.10.0-alpha: building configuration "library"…
pixelperfectengine/src/PixelPerfectEngine/concrete/elements.d(1881,21): Error: function PixelPerfectEngine.concrete.elements.PopUpTextInput.deleteCharacter(int n) is not callable using argument types (ulong)
pixelperfectengine/src/PixelPerfectEngine/concrete/elements.d(1881,21):        cannot pass argument this.cursorPos of type ulong to parameter int n
pixelperfectengine/src/PixelPerfectEngine/concrete/elements.d(1887,20): Error: function PixelPerfectEngine.concrete.elements.PopUpTextInput.deleteCharacter(int n) is not callable using argument types (ulong)
pixelperfectengine/src/PixelPerfectEngine/concrete/elements.d(1887,20):        cannot pass argument this.cursorPos + 1LU of type ulong to parameter int n
../../../../.dub/packages/cpublit-0.4.0-alpha/cpublit/src/CPUblit/composing.d(455,69): Error: cannot cast expression colorV of type __vector(ubyte[16]) to int4
../../../../.dub/packages/cpublit-0.4.0-alpha/cpublit/src/CPUblit/composing.d(470,69): Error: cannot cast expression colorV of type __vector(ubyte[16]) to int4
../../../../.dub/packages/cpublit-0.4.0-alpha/cpublit/src/CPUblit/composing.d(485,70): Error: cannot cast expression colorV of type __vector(ubyte[16]) to int4
pixelperfectengine/src/PixelPerfectEngine/graphics/draw.d(123,23): Error: template instance CPUblit.composing.textBlitter!ubyte error instantiating
../../../../.dub/packages/cpublit-0.4.0-alpha/cpublit/src/CPUblit/composing.d(654,56): Error: cannot cast expression ALPHABLEND_SSE2_MASK of type immutable(__vector(ubyte[16])) to int4
../../../../.dub/packages/cpublit-0.4.0-alpha/cpublit/src/CPUblit/composing.d(669,56): Error: cannot cast expression ALPHABLEND_SSE2_MASK of type immutable(__vector(ubyte[16])) to int4
../../../../.dub/packages/cpublit-0.4.0-alpha/cpublit/src/CPUblit/composing.d(684,56): Error: cannot cast expression ALPHABLEND_SSE2_MASK of type immutable(__vector(ubyte[16])) to int4
pixelperfectengine/src/PixelPerfectEngine/graphics/layers.d(34,14): Error: template instance CPUblit.composing.blitter!uint error instantiating
pixelperfectengine/src/PixelPerfectEngine/graphics/transformFunctions.d(179,22): Error: cannot directly load global variable maskAC with PIC or PIE code
pixelperfectengine/src/PixelPerfectEngine/graphics/transformFunctions.d(180,22): Error: cannot directly load global variable maskAC with PIC or PIE code
pixelperfectengine/src/PixelPerfectEngine/graphics/transformFunctions.d(259,22): Error: cannot directly load global variable maskAC with PIC or PIE code
pixelperfectengine/src/PixelPerfectEngine/graphics/transformFunctions.d(260,22): Error: cannot directly load global variable maskAC with PIC or PIE code
/usr/bin/dmd failed with exit code 1.`

**Comment by ZILtoid1991** [comment]
You should use the LDC compiler, since that has better vector support than DMD, and vectors are used to speed up the rendering. With some hacking you probably can disable it, but it'll have a profound performance impact, especially with alpha blending.

I mainly have tested on 32 bit systems, so there's a few bugs left in, which I'm going to fix in the near future in the next prerelease.

**Comment by ZILtoid1991** [comment]
I did the patch that disallowed compilation on 64 bit systems. Next time I'll try to compile it on Ubuntu too.

**Comment by ZILtoid1991** [comment]
I've done the first tests on Linux, I get linker errors most likely due to zlib.

I'm going to ask around if I can fix that, possibly a missing library.

**Comment by ZILtoid1991** [comment]
I made a new release, fixing the integer issue. You should now be able to compile it under Linux somehow, but I still haven't figured it out.

I couldn't get my linker to see zlib. If you're really hardcore, then you can hack the PNG support out from dimage after it's downloaded by dub.

Also don't forget to use LDC2 as your default compiler as it has a better vector support, which I've used to get stuff running much faster.

**Comment by ZILtoid1991** [comment]
I got it working under Linux.

1) The line `libs "z" platform="Linux"` must be added to dub.sdl, which will be done in the next release.
2) LDC must be used for compiling. DMD64 most likely won't be supported in the foreseeable future due to vast differences how the two handles vectors.
